(define (turtle level size)
    (showturtle)
    (right 60)
    (speed 0)
    (clear)
    (define (loop level size)
        (cond
            ((= level 1)
                (forward size) (left 60)
                (forward size) (left 60)
                (forward size) (left 60)
                (forward size) (left 60)
                (forward size) (left 60)
                (forward size) (left 60)
        ;         (define (loop-hexagon i)
        ;             (if (> i 0)
        ;                 (
        ;                     (forward size)
        ;                     (left 60)
        ;                     (loop-hexagon (- i 1))
        ;                 )
        ;             )
        ;         )
        ;         (loop-hexagon 6)
            )
          (else
                (loop (- level 1) (/ size 2))
                (forward size)
                (left 60)
                (forward size)
                (left 60)
                (loop (- level 1) (/ size 2))
                (forward size)
                (left 60)
                (forward size)
                (left 60)
                (loop (- level 1) (/ size 2))
                (forward size)
                (left 60)
                (forward size)
                (left 60)
                
            )
        )
    )
    (loop level size)
)

(turtle 4 100)